# /cre-node/project.yaml — V4 format (matches --target tenderly-fork)
tenderly-fork:
  rpcs:
    - chain-name: "ethereum-mainnet-base-1"
      url: "https://virtual.base.eu.rpc.tenderly.co/b56974ef-27d1-4492-8975-4a1a99fd4c62"
