# /cre-node/workflow.yaml — V5 Base Sepolia (Pimlico AA pivot)
base-sepolia:
  user-workflow:
    workflow-name: "aegis-oracle-v5"
  workflow-artifacts:
    workflow-path: "./aegis-oracle.ts"
    config-path: "./config.json"
    secrets-path: "./secrets.yaml"
  rpcs:
    - chain-name: "ethereum-testnet-sepolia-base-1"
      url: "https://sepolia.base.org"
