# /cre-node/workflow.yaml — V4 format (matches --target tenderly-fork)
tenderly-fork:
  user-workflow:
    workflow-name: "aegis-oracle-v4"
  workflow-artifacts:
    workflow-path: "./aegis-oracle.ts"
    config-path: "./config.json"
    secrets-path: "./secrets.yaml"
  rpcs:
    - chain-name: "ethereum-mainnet-base-1"
      url: "https://virtual.base.eu.rpc.tenderly.co/fd3b0803-3eea-4603-82c9-245c4bc00209"
